version: '3.8'

services:
  sveltekit:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev -- --host 0.0.0.0
