version: '3.8'

services:
  sveltekit:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://t6291w17uk.execute-api.ap-southeast-1.amazonaws.com
    command: npm run dev -- --host 0.0.0.0
