name: Confirm STAGING_BUCKET_NAME secret

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Show secret length
        shell: bash
        run: |
          echo "STAGING_BUCKET_NAME length: ${#STAGING_BUCKET_NAME}"
        env:
          STAGING_BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
